function bodyFunction() {
	var bodyComp, asideComp, wrapperComp, btnSideNav, headerComp, aboutComp, skillsComp, skillsContainer, h2Skills, h2SkillsText, rowL1SkillsParent, rowL1Skills, pSubtitleSkills, pSubtitleSkillsText, divColm, skillsWrapper, portfolioComp, portFolioContainer, h2Portfolio, h2PortfolioText, rowPortfolioL1, colmPortFolio, anchorsContainer, boxContainer, contactComp, contactContainer, h2Contact, h2ContactText;
	bodyComp = document.createElement('section');
	asideComp = document.createElement('aside');
	asideComp.setAttribute('id', 'sideNavMenu');
	asideComp.setAttribute('class', 'sidenav');
	wrapperComp = document.createElement('main');
	wrapperComp.setAttribute('id', 'wrapper');
	btnSideNav = document.createElement('div');
	btnSideNav.setAttribute('id', 'btn__sideNavigation');
	btnSideNav.setAttribute('class', 'container-btn-menu');
	headerComp = document.createElement('header');
	headerComp.setAttribute('id', 'home');
	headerComp.setAttribute('class', 'section');
	aboutComp = document.createElement('section');
	aboutComp.setAttribute('id', 'about');
	aboutComp.setAttribute('class', 'section container');
	skillsComp = document.createElement('section');
	skillsComp.setAttribute('id', 'skills');
	skillsComp.setAttribute('class', 'section');
	skillsContainer = document.createElement('div');
	skillsContainer.setAttribute('class', 'container');
	h2Skills = document.createElement('h2');
	h2SkillsMark = document.createElement('mark');
	h2Skills.setAttribute('class', 'title-section');
	h2SkillsText =document.createTextNode('MY SKILLS');
	rowL1SkillsParent = document.createElement('div');
	rowL1SkillsParent.setAttribute('class', 'row');
	rowL1Skills = document.createElement('div');
	rowL1Skills.setAttribute('class', 'col-md-3');
	pSubtitleSkills = document.createElement('p');
	pSubtitleSkills.setAttribute('class', 'subTitle');
	pSubtitleSkillsText = document.createTextNode('WEB DEVELOPMENT');
	divColm = document.createElement('div');
	divColm.setAttribute('class', 'col-md-9');
	skillsWrapper = document.createElement('div');
	skillsWrapper.setAttribute('id', 'skills_wrapper');
	skillsWrapper.setAttribute('class', 'row');
	portfolioComp = document.createElement('section');
	portfolioComp.setAttribute('id', 'portfolio');
	portfolioComp.setAttribute('class', 'section');
	portFolioContainer = document.createElement('div');
	portFolioContainer.setAttribute('class', 'container');
	h2Portfolio = document.createElement('h2');
	h2Portfolio.setAttribute('class', 'title-section');
	h2PortfolioMark = document.createElement('mark');
	h2PortfolioText = document.createTextNode('PORTFOLIO');
	rowPortfolioL1 = document.createElement('div');
	rowPortfolioL1.setAttribute('class', 'row');
	colmPortFolio = document.createElement('div');
	colmPortFolio.setAttribute('class', 'col-md-12 text-center');
	boxContainer = document.createElement('br');
	boxContainer.setAttribute('id', 'box__container');
	contactComp = document.createElement('footer');
	contactComp.setAttribute('id', 'contact');
	contactComp.setAttribute('class', 'section');
	contactContainer = document.createElement('div');
	contactContainer.setAttribute('id', 'formWrapper');
	contactContainer.setAttribute('class', 'container container--form');
	h2Contact = document.createElement('h2');
	h2Contact.setAttribute('class', 'text-center');
	h2ContactText = document.createTextNode('CONTACT');

	divColm.appendChild(skillsWrapper);
	pSubtitleSkills.appendChild(pSubtitleSkillsText);
	rowL1Skills.appendChild(pSubtitleSkills)
	rowL1SkillsParent.appendChild(rowL1Skills);
	rowL1SkillsParent.appendChild(divColm);
	h2SkillsMark.appendChild(h2SkillsText);
	h2Skills.appendChild(h2SkillsMark);
	skillsContainer.appendChild(h2Skills);
	skillsContainer.appendChild(rowL1SkillsParent);
	skillsComp.appendChild(skillsContainer);
	//boxContainer.appendChild(boxContainerText);
	colmPortFolio.appendChild(boxContainer);
	
	rowPortfolioL1.appendChild(colmPortFolio);
	h2PortfolioMark.appendChild(h2PortfolioText);
	h2Portfolio.appendChild(h2PortfolioMark);
	portFolioContainer.appendChild(h2Portfolio);
	portFolioContainer.appendChild(rowPortfolioL1);
	portfolioComp.appendChild(portFolioContainer);
	h2Contact.appendChild(h2ContactText);
	contactContainer.appendChild(h2Contact);
	contactComp.appendChild(contactContainer);

	wrapperComp.appendChild(btnSideNav);
	wrapperComp.appendChild(headerComp);
	wrapperComp.appendChild(aboutComp);
	wrapperComp.appendChild(skillsComp);
	wrapperComp.appendChild(portfolioComp);
	wrapperComp.appendChild(contactComp);
	bodyComp.appendChild(asideComp);
	bodyComp.appendChild(wrapperComp);

	document.getElementById('bodyContainer').appendChild(bodyComp);
}